/*
 * Copyright (c) 2021 Toast Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.toasttab.pulseman

// TODO move these all into resource files
object AppStrings {
    const val ADDED = "Added"
    const val ADD_CREDENTIAL_VALUES = "Add your credential values"
    const val ADD_JAR = "Add Jar"
    const val ADD_TAB = "Add tab"
    const val AUTH = "Auth"
    const val AUTH_PARAMETERS = "Auth parameters"
    const val AUTH_SETTINGS = "Auth Settings"
    const val CANCELLED_REPEAT_MESSAGES = "Cancelled repeat messages"
    const val CHARACTER_SET = "Character Set"
    const val CHOOSE_OPTION = "Choose option"
    const val CLASS = "Class"
    const val CLEAR = "Clear"
    const val CLEARED_HISTORY = "Cleared history"
    const val CLEARING = "Clearing..."
    const val CLEAR_LOG = "Clear log"
    const val CLICK_TO_SELECT = "Click to select"
    const val CLOSE_CONNECTION = "Close Connection"
    const val CLOSE_TAB = "Close tab"
    const val CLOSING = "Closing..."
    const val COLLAPSE = "Collapse"
    const val COMMON = "Common"
    const val COMPILE = "Compile"
    const val COMPILING = "Compiling..."
    const val COMPILING_MESSAGE = "Compiling protobuf message"
    const val CONFLICT_WARNING = "WARNING file may cause conflicts"
    const val CONNECTION_CLOSED = "Connection closed"
    const val CONVERT = "Convert"
    const val CONVERTING = "Converting"
    const val COPY = "Copy"
    const val COPY_CURRENT_TAB = "Copy current tab"
    const val COULD_NOT_TRANSMIT_TOPIC = "Could not transmit on topic"
    const val CREATING_NEW_PRODUCER = "Creating new producer"
    const val DELAY_MS = "Delay(ms)"
    const val DELETED_CLASS_FEEDBACK = "Selected class was in deleted file and is no longer available"
    const val DELETE_ALL = "Delete all"
    const val DELETE_JAR = "Delete jar"
    const val ELLIPSIS = "…"
    const val ENTER_VALUE = "Enter Value"
    const val EXCEPTION = "Exception"
    const val EXPAND = "Expand"
    const val EXITING_REPEAT_LOOP = "Exiting repeat loop"
    const val FAILS = "Fails"
    const val FAIL_TO_SUBSCRIBE = "Fail to subscribe"
    const val FAILED_TO_CLOSE_PULSAR = "Failed to close pulsar"
    const val FAILED_TO_CONVERT_BYTES = "Failed to convert bytes"
    const val FAILED_TO_CREATE_CONSUMER = "Failed to create consumer"
    const val FAILED_TO_CREATE_DIRECTORY = "Failed to create directory"
    const val FAILED_TO_CREATE_PRODUCER = "Failed to create producer"
    const val FAILED_TO_DESERIALIZE_PROPERTIES = "Failed to deserialize properties"
    const val FAILED_TO_DESERIALIZE_PULSAR = "Failed to deserialize pulsar"
    const val FAILED_TO_LOAD_PROJECT = "Failed to load project"
    const val FAILED_TO_RETRIEVE_TOPICS = "Failed to retrieve topics"
    const val FAILED_TO_SEND_MESSAGE = "Failed to send message"
    const val FAILED_TO_SETUP_PULSAR = "Failed to setup pulsar"
    const val FILE = "File"
    const val FILTER = "Filter"
    const val FILTER_PULSAR = "Filter Pulsar Jars"
    const val GENERATE = "Generate"
    const val GENERATED_CLASS_NOT_SAME_AS_SELECTED = "Generated class not the same as selected class"
    const val GENERATED_CODE_TEMPLATE = "Generated code template"
    const val GENERATING = "Generating..."
    const val GRADLE_ERROR = "Error running Gradle task"
    const val GRADLE = "Gradle"
    const val GRADLE_ALREADY_RUNNING = "failed gradle already running"
    const val JARS = "Jars"
    const val JAR_FILE_DIALOG_TITLE = "Select JAR files"
    const val JAVA_HOME_ERROR = "Java home must be valid for gradle JAVA_HOME:"
    const val LOADING = "Loading..."
    const val LOAD_PROJECT = "Load project"
    const val LOAD_TOPICS = "Load topics"
    const val MANAGE_JARS = "Manage jars"
    const val MESSAGE = "Message"
    const val MESSAGE_SENT_ID = "Message sent with id"
    const val MS = "ms"
    const val NAME = "Name"
    const val NEW_TAB = "New tab"
    const val NO_CLASS_GENERATED_TO_SEND = "No class generated to send"
    const val NO_CLASS_SELECTED = "No class selected"
    const val NO_CLASS_SELECTED_DESERIALIZE = "No class selected to deserialize"
    const val NO_VALID_CLASSES_LOADED = "No valid classes loaded"
    const val NO_TOPICS_FOUND = "No topics found"
    const val ON_TOPIC = "on topic"
    const val PROJECT_LOAD = "project load"
    const val PROJECT_FILE_DIALOG_TITLE = "Select Project File"
    const val PROTO_CLASS_NOT_SELECTED = "Proto class not selected"
    const val PROPERTIES = "Properties"
    const val PULSAR_URL = "Pulsar URL"
    const val PULSEMAN = "Pulseman"
    const val RECEIVE = "Receive"
    const val RECOMPILE = "Recompile"
    const val REMOVED = "Removed"
    const val REPEAT = "Repeat"
    const val RETRYING = "Retrying"
    const val RUNNING_GRADLE_TASK = "Running Gradle task"
    const val RUN = "Run"
    const val RUNNING = "Running..."
    const val RUNS = "Runs"
    const val SAVE = "Save"
    const val SAVE_AS = "Save as"
    const val SAVE_FILE_DIALOG_TITLE = "Save Project"
    const val SEARCH_FOR_TOPIC = "Search for topic"
    const val SELECT = "Select"
    const val SELECT_TOPIC = "Select topic"
    const val SELECTED = "Selected"
    const val SELECTED_CHARSET = "Selected charset"
    const val SELECTED_SEND_CHARSET = "Selected send charset"
    const val SELECTED_CLASS = "Selected class"
    const val SEND = "Send"
    const val SENDING = "Sending..."
    const val SENDING_PROTOBUF = "Sending protobuf message"
    const val SEND_TIME = "Send Time"
    const val SERIALIZATION = "Serialization"
    const val SERIALIZATION_FORMAT = "serialization format"
    const val SERVICE_URL = "Service Url"
    const val SERVICE_URL_NOT_SET = "Service Url is not set"
    const val SETUP = "setup"
    const val SET_AUTHORIZATION_VALUES = "Set Authorization Values"
    const val SET_MESSAGE_PROPERTY_VALUES = "Set message property values"
    const val SETTING_UP_GRADLE = "Setting up gradle..."
    const val SLEPT = "Slept"
    const val STOP = "Stop"
    const val SUBSCRIBE = "Subscribe"
    const val SUBSCRIBED = "Subscribed"
    const val SUBSCRIBING = "Subscribing..."
    const val SUCCESSFULLY_COMPILED_CLASS = "Successfully compiled class"
    const val TAB_NAME = "Tab Name"
    const val TODO = "TODO"
    const val TOPIC = "Topic"
    const val TOPIC_NOT_SET = "Topic is not set"
    const val WAIT_SEND_TO_FINISH = "Waiting for last send to finish"
    const val WAIT_SEND_TO_FINISH_ERROR = "Waiting to finish errored out"
    const val UNSAVED_CHANGES_DIALOG_MESSAGE = "Do you want to save your changes?"
    const val UNSAVED_CHANGES_DIALOG_TITLE = "Unsaved changes"
    const val UNSELECTED = "Unselected"
}
